#include <iostream>
#include "ros/ros.h"
#include "vehicle.h"
#include "utility.h"
#include <visualization_msgs/Marker.h>
#include <memory>
#include <thread>
#include <mutex>
#include <atomic>
#include "mymsg/neighborpos.h"
#include "mymsg/refpos.h"
#include "std_msgs/String.h"
