self:
  id: 2
  ip: 127.0.0.1
remote: # 目前只会读第一组
  - id: 1
    ip: 192.168.31.101
    send_port: 40001 # 要根据车号改正
    recv_port: 30001
    send_topics:
      - /Odometry #nav_msgs::Odometry
      - /cat_state #std_msgs::Bool
    recv_topics:
      - /cmd_vel #geometry_msgs::Twist
      - /cat_cmd #std_msgs::Bool